### 업무 등록
POST /api/projects/1/tasks
Host: localhost:9090
Content-Type: application/json

{
  "title": "미니두레이 ERD 설계2",
  "content": "ERD 설계 열심히 하기2",
  "writerId": 1,
  "endDate": "2023-06-01",
  "memberIds": [1, 2],
  "milestoneId": 1,
  "tagIds": [2, 3]
}

### 업무 등록
POST /api/projects/1/tasks
Host: localhost:9090
Content-Type: application/json

{
  "title": "미니두레이 ERD 설계2",
  "content": "ERD 설계 열심히 하기2",
  "writerId": 1
}

### 업무 수정
PUT /api/projects/1/tasks/3
Host: localhost:9090
Content-Type: application/json

{
  "title": "미니두레이 ERD 설계 수정",
  "content": "ERD 설계 열심히 하기 수정",
  "endDate": "2023-06-10",
  "memberIds": [1, 2],
  "milestoneId": 2,
  "tagIds": [4]
}

### 업무 수정
PUT /api/projects/1/tasks/3
Host: localhost:9090
Content-Type: application/json

{
  "title": "미니두레이 ERD 설계 수정",
  "content": "ERD 설계 열심히 하기 수정",
  "endDate": "2023-06-10"
}

### 업무 삭제
DELETE /api/projects/8/tasks/8
Host: localhost:9090
Content-Type: application/json

### 프로젝트 아이디로 업무 조회
GET /api/projects/1/tasks
Host: localhost:9090
Content-Type: application/json

### 업무 아이디로 업무 조회